'use strict';

function renderConfig(profile, dataDir) {
  const lines = [];
  lines.push('# Generated by cc-connect-profile-manager. This is a standard cc-connect config.');
  lines.push(`data_dir = ${tomlString(dataDir)}`);
  lines.push(`language = ${tomlString(profile.language)}`);
  lines.push('');
  lines.push('[log]');
  lines.push(`level = ${tomlString(profile.log_level)}`);
  lines.push('');
  lines.push('[management]');
  lines.push('enabled = true');
  lines.push(`port = ${profile.management_port}`);
  lines.push(`token = ${tomlString(profile.management_token)}`);
  lines.push('cors_origins = ["*"]');
  lines.push('');
  lines.push('[bridge]');
  lines.push('enabled = true');
  lines.push(`port = ${profile.bridge_port}`);
  lines.push(`token = ${tomlString(profile.bridge_token)}`);
  if (profile.bridge_path) lines.push(`path = ${tomlString(profile.bridge_path)}`);
  lines.push('cors_origins = ["*"]');
  lines.push('');
  lines.push('[[providers]]');
  lines.push(`name = ${tomlString(profile.provider.name)}`);
  if (profile.provider.api_key) lines.push(`api_key = ${tomlString(profile.provider.api_key)}`);
  if (profile.provider.base_url) lines.push(`base_url = ${tomlString(profile.provider.base_url)}`);
  if (profile.provider.model) lines.push(`model = ${tomlString(profile.provider.model)}`);
  appendMap(lines, 'providers.env', profile.provider.env);
  lines.push('');
  lines.push('[[projects]]');
  lines.push(`name = ${tomlString(profile.project_name)}`);
  lines.push('');
  lines.push('[projects.agent]');
  lines.push(`type = ${tomlString(profile.agent_type)}`);
  lines.push(`provider_refs = [${tomlString(profile.provider.name)}]`);
  lines.push('');
  lines.push('[projects.agent.options]');
  lines.push(`work_dir = ${tomlString(profile.work_dir)}`);
  lines.push(`mode = ${tomlString(profile.agent_mode)}`);
  lines.push(`provider = ${tomlString(profile.provider.name)}`);
  if (profile.agent_model) lines.push(`model = ${tomlString(profile.agent_model)}`);
  lines.push('');
  lines.push('[[projects.platforms]]');
  lines.push(`type = ${tomlString(profile.platform.type)}`);
  lines.push('');
  lines.push('[projects.platforms.options]');
  appendMap(lines, '', profile.platform.options);
  return `${lines.join('\n')}\n`;
}

function appendMap(lines, table, values) {
  const keys = Object.keys(values || {}).filter(Boolean).sort();
  if (!keys.length) return;
  if (table) lines.push(`[${table}]`);
  for (const key of keys) {
    const value = values[key];
    if (value === '' || value == null) continue;
    if (typeof value === 'boolean' || typeof value === 'number') {
      lines.push(`${key} = ${JSON.stringify(value)}`);
    } else {
      lines.push(`${key} = ${tomlString(String(value))}`);
    }
  }
}

function tomlString(value) {
  return JSON.stringify(String(value == null ? '' : value));
}

module.exports = { renderConfig, tomlString };
